In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
bc=datasets.load_breast_cancer()
X=bc.data
y=bc.target

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0,stratify=y)

In [7]:
class CustomPerceptron(object):

    def __init__(self,n_iterations=1000,random_state=1,learning_rate=0.01):
        self.n_iterations=n_iterations
        self.random_state=random_state
        self.learning_rate=learning_rate

def fit(self,X,y):
    rgen=np.random.RandomState(self.random_state)
    self.coef_=rgen.normal(loc=0.0,scale=0.01,size=1+X.shape[1])
    for _ in range(self.n_iterations):
        for xi,expected_value in zip(X,y):
            predicted_value=self.predict(xi)
            self.coef_[1]+=self.learning_rate*(expected_value-predicted_value)*xi
            self_coef_[0]+=self.learning_rate*(expected_value-predicted_value)*1

def activation(self,X):
    return np.dot(X,self.coef_[1])+self.coef_[0]

def predict(self,X):
    output=self.activation(X)
    return np.where(op>=0.0,1,0)

def score(self,X,y):
    misclassified_data_count=0
    for xi,target in zip(X,y):
        output=self.predict(xi)
        if(target!=output):
            misclassified_data_count+=1
            total_data_count=len(X)
            self_score=(total_data_count-misclassified_data_count)/total_data_count
            return self.score_      

In [9]:
n_iterations=1000
learning_rate=0.01

In [11]:
print(X_train,y_train)

[[1.320e+01 1.743e+01 8.413e+01 ... 4.970e-02 2.767e-01 7.198e-02]
 [1.122e+01 3.381e+01 7.079e+01 ... 3.002e-02 2.911e-01 7.307e-02]
 [1.454e+01 2.754e+01 9.673e+01 ... 1.712e-01 4.218e-01 1.341e-01]
 ...
 [1.106e+01 1.496e+01 7.149e+01 ... 1.075e-01 3.301e-01 9.080e-02]
 [1.199e+01 2.489e+01 7.761e+01 ... 1.202e-01 2.599e-01 8.251e-02]
 [1.239e+01 1.748e+01 8.064e+01 ... 9.804e-02 2.819e-01 1.118e-01]] [1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0
 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 0 0 0 1 1
 1 0 1 0 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0
 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1
 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1
 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 1 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1
 0 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0 1 0 0 0 0 1 1 1 1 

In [13]:
print(X_test,y_test)

[[1.708e+01 2.715e+01 1.112e+02 ... 1.555e-01 3.010e-01 9.060e-02]
 [1.277e+01 2.247e+01 8.172e+01 ... 9.331e-02 2.829e-01 8.067e-02]
 [1.425e+01 2.215e+01 9.642e+01 ... 1.785e-01 2.844e-01 1.132e-01]
 ...
 [1.300e+01 2.078e+01 8.351e+01 ... 6.296e-02 3.196e-01 6.435e-02]
 [1.481e+01 1.470e+01 9.466e+01 ... 7.955e-02 2.334e-01 6.142e-02]
 [9.720e+00 1.822e+01 6.073e+01 ... 0.000e+00 1.909e-01 6.559e-02]] [0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1
 0 1 0 0 0 1 0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 1 0 1 0 1 0 1 1 1
 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1]


X_train,y_train,X_test,y_test are shown in this matrix is exponentially and in the form of 0 & 1.